### ISSUE TITLE
netexe and netwindows file sources

### ISSUE THREAD

**Issue by Cornelius2121** [bormaa/Benign-NET#1]
Hi there,

Interested to know where the files within netexe and netwindows were sourced from. Thanks very much.

**Comment by bormaa** [comment]
Hi,
The netwindows were collected from installed windows files in system32 and other places.
The netexe don't remember exactly from where but i will try tp figure out

**Comment by Cornelius2121** [comment]
Thanks very much. Would be very helpful to know about netexe as I am using this dataset in a paper and am keen to discuss the dataset and cite the GitHub (unless there is a publication for this dataset that I don't know about :) )

**Comment by bormaa** [comment]
Hello bro,
After checking some files I believe they also belong to Sourceforge.
I can provide you with a bigger dataset with exe files not only, .NET files 
A paper will be published soon but I don't mind that you use my dataset and cite it

**Comment by arjunsinghbisht94** [comment]
sir can you please provide me all 14000 benign executables???????
arjunbisht22may@gmail.com

**Comment by bormaa** [comment]
The repo already contain them. But I have other but they are not .NET files will send you the link

**Comment by arjunsinghbisht94** [comment]
Sir please send me link so that I could download it..

**Comment by arjunsinghbisht94** [comment]
Respected Sir,

I apologize for any inconvenience, but I am in need of your guidance as I
am working on network malware research. I require various network malware
executables, such as Emotet, NOise, Trick Bot, DDoSer, CryptoLocker, and
others, for my study. If you have any sources that can provide me with
these executables, kindly guide me on how to collect them. Your assistance
will be highly appreciated, and I will be very thankful to you.

Thank you for your understanding.

**Comment by bormaa** [comment]
@arjunsinghbisht94  please check other projects like https://www.vx-underground.org/ may help you
